Console.WriteLine("HW#2");
Console.WriteLine("Task#1");
Console.WriteLine("Enter the value a");
int a = int.Parse(Console.ReadLine());
Console.WriteLine("Enter the value b");
int b = int.Parse(Console.ReadLine());
Console.WriteLine($"a={a}, b={b}");
Console.WriteLine($"a+b= {a + b}");
Console.WriteLine($"a-b= {a - b}");
Console.WriteLine($"a*b= {a * b}");
Console.WriteLine($"a/b= {a / b}");
Console.WriteLine("Task#2");
Console.WriteLine("How are you?");
string answer = Console.ReadLine();
Console.WriteLine($"You are {answer}");
Console.WriteLine("Task#3");
Console.WriteLine("Enter 1 variabele");
char x = char.Parse(Console.ReadLine());
Console.WriteLine("Enter 2 variabele");
char y = char.Parse(Console.ReadLine());
Console.WriteLine("Enter 3 variabele");
char z = char.Parse(Console.ReadLine());
Console.WriteLine($"You entered {x}, {y}, {z}");
Console.WriteLine("Task#4");
Console.WriteLine("Enter first number");
int k = int.Parse(Console.ReadLine());
Console.WriteLine("Enter second number");
int t = int.Parse(Console.ReadLine());
bool firstNumber = k > 0;
bool secondNumber = t > 0;
bool bothPositive = k > 0 && t > 0;
Console.WriteLine("first integer is positive: " + firstNumber);
Console.WriteLine("first integer is positive: " + secondNumber);
Console.WriteLine("Both numbers are positive: " + bothPositive);
Console.WriteLine("Task#5");
Console.WriteLine("Enter the value of the side of the square");
double c = double.Parse(Console.ReadLine());
Console.WriteLine($"Perimeter of the square= {4 * c}");
Console.WriteLine($"Area of the square= {c * c}");
Console.WriteLine("Task#6");
string name = "Uliana";
int age = 37;
Console.WriteLine("What is your name?");
Console.WriteLine($"My name is {name}");
Console.WriteLine("How old are you, {0}", name);
Console.WriteLine("I am {0} years old", age);
Console.WriteLine("Task#7");
Console.WriteLine("Enter the circle radius value");
double r = double.Parse(Console.ReadLine());
double area = Math.PI * r * r;
double length = 2 * Math.PI * r;
double volume = 4 / 3 * Math.PI * r * r * r;
Console.WriteLine("Length is {0:N2}", length);
Console.WriteLine("Area of the square is {0:N2}", area);
Console.WriteLine("Volume is {0:N2}", volume);

